package executor

import (
	"fmt"
	"os/exec"
	"strings"
	"time"

	"github.com/taasezer/TaaNOS/internal/interaction"
	"github.com/taasezer/TaaNOS/internal/planner"
)

// Engine executes validated plans step-by-step.
// Commands are NEVER generated by AI — they come from the hardcoded action registry.
type Engine struct {
	dryRun bool
}

// NewEngine creates an executor engine.
func NewEngine(dryRun bool) *Engine {
	return &Engine{dryRun: dryRun}
}

// Execute runs all approved steps in the plan.
func (e *Engine) Execute(
	plan *planner.ExecutionPlan,
	decision *interaction.UserDecision,
	mode string,
) *ExecutionResult {

	result := &ExecutionResult{
		PlanID:      plan.PlanID,
		StepsTotal:  len(plan.Steps),
		StepResults: []StepResult{},
	}

	skippedSet := make(map[int]bool)
	for _, id := range decision.SkippedSteps {
		skippedSet[id] = true
	}

	startTime := time.Now()

	for _, step := range plan.Steps {
		// Skip if user chose to skip this step
		if skippedSet[step.ID] {
			result.StepResults = append(result.StepResults, StepResult{
				StepID:    step.ID,
				Status:    "skipped",
				Timestamp: time.Now(),
			})
			fmt.Printf("  ⏭ Step %d/%d: %s — skipped\n", step.ID, result.StepsTotal, step.Description)
			continue
		}

		// Execute the step
		stepResult := e.executeStep(step, result.StepsTotal, mode)
		result.StepResults = append(result.StepResults, stepResult)

		if stepResult.Status == "success" {
			result.StepsCompleted++
		} else if stepResult.Status == "failed" {
			if !step.CanFail {
				// Critical step failed — stop execution
				result.Status = ExecFailure
				result.TotalDuration = time.Since(startTime)
				return result
			}
			// Non-critical step failed — continue
			fmt.Printf("  ⚠️  Step %d failed but is non-critical, continuing...\n", step.ID)
		}
	}

	// Determine overall status
	if result.StepsCompleted == result.StepsTotal {
		result.Status = ExecSuccess
	} else if result.StepsCompleted > 0 {
		result.Status = ExecPartialFailure
	} else {
		result.Status = ExecFailure
	}

	result.TotalDuration = time.Since(startTime)
	return result
}

// executeStep runs a single step and captures the result.
func (e *Engine) executeStep(step planner.ExecutionStep, total int, mode string) StepResult {
	sr := StepResult{
		StepID:    step.ID,
		Timestamp: time.Now(),
	}

	// Dry run — show what would be executed
	if e.dryRun {
		fmt.Printf("  🔸 Step %d/%d: %s [dry-run]\n", step.ID, total, step.Description)
		if step.RequiresRoot {
			fmt.Printf("    → sudo %s\n", step.CommandTemplate)
		} else {
			fmt.Printf("    → %s\n", step.CommandTemplate)
		}
		sr.Status = "success"
		sr.ExitCode = 0
		return sr
	}

	// Real execution
	fmt.Printf("  ▶ Step %d/%d: %s\n", step.ID, total, step.Description)

	// Build the command
	cmdStr := step.CommandTemplate
	var cmd *exec.Cmd

	if step.RequiresRoot {
		// Use sudo
		fmt.Printf("    → sudo %s\n", cmdStr)
		cmd = exec.Command("sudo", "bash", "-c", cmdStr)
	} else {
		fmt.Printf("    → %s\n", cmdStr)
		cmd = exec.Command("bash", "-c", cmdStr)
	}

	start := time.Now()

	// Execute with timeout
	output, err := runWithTimeout(cmd, step.Timeout)
	sr.Duration = time.Since(start)

	if err != nil {
		sr.Status = "failed"
		sr.Stderr = err.Error()
		if exitErr, ok := err.(*exec.ExitError); ok {
			sr.ExitCode = exitErr.ExitCode()
		} else {
			sr.ExitCode = -1
		}
		// Show truncated output
		if len(output) > 0 {
			sr.Stdout = truncate(string(output), 500)
		}
		fmt.Printf("    ✗ Failed (exit=%d, %s)\n", sr.ExitCode, sr.Duration.Round(time.Millisecond))
		if sr.Stderr != "" {
			fmt.Printf("    Error: %s\n", truncate(sr.Stderr, 200))
		}
	} else {
		sr.Status = "success"
		sr.ExitCode = 0
		sr.Stdout = truncate(string(output), 500)
		fmt.Printf("    ✓ Completed (%s)\n", sr.Duration.Round(time.Millisecond))
	}

	return sr
}

// runWithTimeout executes a command with a timeout.
func runWithTimeout(cmd *exec.Cmd, timeout time.Duration) ([]byte, error) {
	if timeout <= 0 {
		timeout = 120 * time.Second
	}

	type result struct {
		output []byte
		err    error
	}

	done := make(chan result, 1)
	go func() {
		out, err := cmd.CombinedOutput()
		done <- result{out, err}
	}()

	select {
	case r := <-done:
		return r.output, r.err
	case <-time.After(timeout):
		if cmd.Process != nil {
			cmd.Process.Kill()
		}
		return nil, fmt.Errorf("command timed out after %s", timeout)
	}
}

// truncate limits a string to maxLen characters.
func truncate(s string, maxLen int) string {
	s = strings.TrimSpace(s)
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen] + "..."
}
